name: Publish Helm Chart (non_Dynamic version)

on:
  workflow_run:
    workflows:
      - "Build and Push Docker Images"
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: "Package Helm Chart"  
        run: |
            cd helm
            rm -f *.tgz
            helm package monolithic-website
          
      - name: 'Upload Helm Chart to gcp cloud storage'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'helm/monolithic-website-0.1.0.tgz'
          destination: 'boma-helm-repo/charts/'

      - name: Generate or Update Helm Chart Index
        run: helm repo index --url http://storage.googleapis.com/boma-helm-repo/charts/ .

      - name: 'Upload index.yaml to gcp cloud storage'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'helm/index.yaml'
          destination: 'boma-helm-repo/charts/'

      - name: 'Install the Helm gcp storage plugin'
        run: helm plugin install https://github.com/viglesiasce/helm-gcs.git

      - name: Configure Helm Repository
        #uses: 'google-github-actions/upload-cloud-storage@v1'
        run: helm repo add monolith-website gs://boma-helm-repo/charts/

      - name: Push Helm Chart to gcs Repository
        run: helm gcs push --force helm/monolithic-website-0.1.0.tgz monolithic-website

      #33tttuuuuuuummmmmmeeeee